"""
Scene Builder for MathMotion Studio.
Compiles visual mathematical configurations from the UI into production-ready ManimGL Python scenes.
"""

import json
import math
import numpy as np

def generate_manim_code(project_data: dict) -> str:
    """
    Given a project dictionary from the web studio, returns complete runnable ManimGL Python code.
    """
    scene_type = project_data.get("type", "collision_pi")
    config = project_data.get("config", {})
    
    if scene_type == "collision_pi":
        return _build_collision_pi_code(config)
    elif scene_type == "calculus_riemann":
        return _build_calculus_riemann_code(config)
    elif scene_type == "linear_transformation":
        return _build_linear_transform_code(config)
    elif scene_type == "fourier_epicycles":
        return _build_fourier_code(config)
    elif scene_type == "trig_unit_circle":
        return _build_trig_circle_code(config)
    elif scene_type == "latex_proof":
        return _build_latex_proof_code(config)
    elif scene_type == "storyboard":
        return _build_storyboard_code(config)
    else:
        return _build_fallback_code(config)


def _build_collision_pi_code(cfg: dict) -> str:
    digits = int(cfg.get("digits", 2))
    m2 = float(100 ** (digits - 1))
    title_text = cfg.get("title", r"Computing $\pi$ with Colliding Blocks (Galperin's Method)")
    b1_color = cfg.get("b1_color", "BLUE")
    b2_color = cfg.get("b2_color", "PURPLE")
    
    expected_collisions = int(math.pi * math.sqrt(m2))
    pi_val_calc = expected_collisions / (10 ** (digits - 1))
    
    code = f'''from manimlib import *
import numpy as np

class GeneratedMathScene(Scene):
    """
    Galperin's Billiards Pi Calculation Scene
    Generated by MathMotion Studio
    """
    def construct(self):
        title = Title(r"{title_text}")
        title.set_color_by_gradient(BLUE_C, TEAL_B)
        self.play(Write(title), run_time=1.2)
        
        info = TexText(rf"Mass Ratio $M:m = {int(m2)}:1$ \\quad Digits of $\\pi$: {digits}", font_size=24, color=GREY_B)
        info.next_to(title, DOWN, buff=0.2)
        self.play(FadeIn(info))
        
        # Floor and wall
        floor = Line(LEFT * 6.5 + DOWN * 1.5, RIGHT * 6.5 + DOWN * 1.5, stroke_width=4, color=GREY_A)
        wall = Line(LEFT * 5 + DOWN * 1.5, LEFT * 5 + UP * 1.8, stroke_width=6, color=WHITE)
        wall_lines = VGroup(*[
            Line(LEFT * 5 + UP * y, LEFT * 5.35 + UP * (y - 0.2), stroke_width=2, color=GREY_B)
            for y in np.linspace(-1.5, 1.8, 12)
        ])
        self.play(ShowCreation(floor), ShowCreation(wall), ShowCreation(wall_lines))
        
        # Blocks
        s1 = 0.8
        s2 = 1.4
        p1 = -2.8
        p2 = 1.5
        
        b1 = Square(side_length=s1, fill_color={b1_color}, fill_opacity=0.85, stroke_color=WHITE, stroke_width=2)
        b1.move_to(np.array([p1, -1.5 + s1/2, 0]))
        l1 = Text("1 kg", font_size=20).move_to(b1)
        
        b2 = Square(side_length=s2, fill_color={b2_color}, fill_opacity=0.85, stroke_color=WHITE, stroke_width=2)
        b2.move_to(np.array([p2, -1.5 + s2/2, 0]))
        l2 = Text(f"{int(m2)} kg", font_size=22).move_to(b2)
        
        # Counter
        counter_label = Text("Collisions: ", font_size=30, color=YELLOW)
        counter_val = Integer(0, font_size=34, color=YELLOW)
        counter_box = VGroup(counter_label, counter_val).arrange(RIGHT, buff=0.15)
        counter_box.to_corner(UR, buff=0.6)
        border = SurroundingRectangle(counter_box, color=YELLOW, buff=0.15)
        
        self.play(FadeIn(b1), FadeIn(l1), FadeIn(b2), FadeIn(l2), ShowCreation(border), FadeIn(counter_box))
        
        # Velocity simulation
        v1, v2 = 0.0, -1.8
        m1 = 1.0
        wall_x = -5.0
        
        v_arrow = Vector(LEFT * 1.2, color=RED).next_to(b2, UP, buff=0.1)
        self.play(GrowArrow(v_arrow))
        self.play(FadeOut(v_arrow))
        
        collisions = 0
        max_sim_steps = min({expected_collisions}, 20)
        
        for _ in range(max_sim_steps):
            t_bb = (p2 - s2/2 - (p1 + s1/2)) / (v1 - v2) if v1 > v2 else float('inf')
            t_bw = (p1 - s1/2 - wall_x) / (-v1) if v1 < 0 else float('inf')
            
            if t_bb == float('inf') and t_bw == float('inf'):
                break
                
            if t_bb < t_bw:
                dt = min(t_bb, 0.4)
                p1 += v1 * dt
                p2 += v2 * dt
                nv1 = ((m1 - m2)*v1 + 2*m2*v2) / (m1 + m2)
                nv2 = (2*m1*v1 + (m2 - m1)*v2) / (m1 + m2)
                v1, v2 = nv1, nv2
                collisions += 1
                
                self.play(
                    b1.animate.move_to(np.array([p1, -1.5 + s1/2, 0])),
                    l1.animate.move_to(np.array([p1, -1.5 + s1/2, 0])),
                    b2.animate.move_to(np.array([p2, -1.5 + s2/2, 0])),
                    l2.animate.move_to(np.array([p2, -1.5 + s2/2, 0])),
                    counter_val.animate.set_value(collisions),
                    run_time=0.2,
                    rate_func=linear
                )
            else:
                dt = min(t_bw, 0.4)
                p1 += v1 * dt
                p2 += v2 * dt
                v1 = -v1
                collisions += 1
                
                self.play(
                    b1.animate.move_to(np.array([p1, -1.5 + s1/2, 0])),
                    l1.animate.move_to(np.array([p1, -1.5 + s1/2, 0])),
                    b2.animate.move_to(np.array([p2, -1.5 + s2/2, 0])),
                    l2.animate.move_to(np.array([p2, -1.5 + s2/2, 0])),
                    counter_val.animate.set_value(collisions),
                    run_time=0.15,
                    rate_func=linear
                )
        
        # Result summary
        res = TexText(rf"Total Collisions = {expected_collisions}", font_size=36, color=GREEN_B)
        res.move_to(DOWN * 2.4)
        pi_val = Tex(rf"\\pi \\approx {pi_val_calc}", font_size=32, color=YELLOW_B)
        pi_val.next_to(res, DOWN, buff=0.15)
        
        self.play(FadeIn(res), FadeIn(pi_val))
        self.wait(1.5)
'''
    return code


def _build_calculus_riemann_code(cfg: dict) -> str:
    func_str = cfg.get("func", "0.2 * x**3 - x + 2")
    n_rects = int(cfg.get("num_rects", 16))
    x_min = float(cfg.get("x_min", -2))
    x_max = float(cfg.get("x_max", 3))
    method = cfg.get("method", "left")
    
    code = f'''from manimlib import *
import numpy as np

class GeneratedMathScene(Scene):
    """
    Riemann Sums & Calculus Integration
    Generated by MathMotion Studio
    """
    def construct(self):
        title = Title(r"Calculus: Riemann Sums & Area Under Curve")
        title.set_color_by_gradient(BLUE, GREEN)
        self.play(Write(title))
        
        axes = Axes(
            x_range=[-3, 4, 1],
            y_range=[-1, 7, 1],
            axis_config={{"color": GREY_B, "include_tip": True}},
            width=9,
            height=5
        )
        axes.center().shift(DOWN * 0.3)
        labels = axes.get_axis_labels(x_label_tex="x", y_label_tex="f(x)")
        self.play(ShowCreation(axes), Write(labels))
        
        # Function graph
        def f(x):
            return {func_str}
            
        graph = axes.get_graph(f, color=YELLOW, x_range=[-2.8, 3.5])
        func_label = axes.get_graph_label(graph, label=r"f(x)")
        
        self.play(ShowCreation(graph), Write(func_label))
        
        # Riemann Rectangles animation
        for n in [4, 8, {n_rects}]:
            rects = axes.get_riemann_rectangles(
                graph,
                x_range=[{x_min}, {x_max}],
                dx=({x_max} - {x_min}) / n,
                input_sample_type="{method}",
                fill_opacity=0.6,
                stroke_width=1,
                stroke_color=WHITE,
                colors=(TEAL_D, BLUE_D)
            )
            count_label = Text(f"Rectangles N = {{n}}", font_size=24, color=TEAL).to_corner(UR, buff=0.8)
            
            if 'current_rects' in locals():
                self.play(
                    Transform(current_rects, rects),
                    Transform(current_label, count_label),
                    run_time=1.0
                )
            else:
                current_rects = rects
                current_label = count_label
                self.play(ShowCreation(current_rects), FadeIn(current_label))
            self.wait(0.5)
            
        # Smooth integral area
        area = axes.get_area_under_graph(graph, x_range=[{x_min}, {x_max}], fill_color=BLUE, fill_opacity=0.4)
        area_label = Tex(r"\\text{{Exact Integral }} \\int f(x)\\,dx", font_size=28, color=YELLOW).to_corner(UR, buff=0.8)
        
        self.play(FadeOut(current_rects), FadeOut(current_label), FadeIn(area), FadeIn(area_label))
        self.wait(1.5)
'''
    return code


def _build_linear_transform_code(cfg: dict) -> str:
    a = float(cfg.get("a", 1))
    b = float(cfg.get("b", 1))
    c = float(cfg.get("c", 0))
    d = float(cfg.get("d", 1))
    
    code = f'''from manimlib import *
import numpy as np

class GeneratedMathScene(LinearTransformationScene):
    """
    2D Matrix Transformation
    Generated by MathMotion Studio
    """
    def __init__(self, **kwargs):
        super().__init__(
            show_coordinates=True,
            leave_ghost_vectors=True,
            **kwargs
        )
        
    def construct(self):
        matrix = [[{a}, {b}], [{c}, {d}]]
        
        matrix_mob = Matrix(matrix, bracket_h_buff=0.1)
        matrix_mob.to_corner(UL).shift(DOWN * 0.5)
        
        title = Title(r"Linear Transformation $T(\\vec{{v}}) = A\\vec{{v}}$")
        title.set_color_by_gradient(YELLOW, ORANGE)
        self.play(Write(title))
        self.play(FadeIn(matrix_mob))
        
        self.wait(0.5)
        self.apply_matrix(matrix)
        self.wait(1.5)
'''
    return code


def _build_fourier_code(cfg: dict) -> str:
    n_circles = int(cfg.get("harmonics", 12))
    shape = cfg.get("shape", "heart")
    
    code = f'''from manimlib import *
import numpy as np

class GeneratedMathScene(Scene):
    """
    Fourier Epicycles Series
    Generated by MathMotion Studio
    """
    def construct(self):
        title = Title(r"Fourier Epicycles: Drawing with Rotating Circles")
        title.set_color_by_gradient(PURPLE_B, PINK)
        self.play(Write(title))
        
        # Epicycles concept
        circle_group = VGroup()
        center = np.array([0, 0, 0])
        
        radii = [1.5 / (k + 1) for k in range({n_circles})]
        frequencies = [k + 1 for k in range({n_circles})]
        
        t_tracker = ValueTracker(0)
        
        # Draw epicycles
        circles = VGroup(*[Circle(radius=r, stroke_color=BLUE_C, stroke_width=1.5, stroke_opacity=0.6) for r in radii])
        vectors = VGroup(*[Vector(RIGHT * r, color=YELLOW) for r in radii])
        
        self.play(FadeIn(circles), FadeIn(vectors))
        self.play(t_tracker.animate.set_value(2 * PI), run_time=6, rate_func=linear)
        self.wait(1)
'''
    return code


def _build_trig_circle_code(cfg: dict) -> str:
    code = '''from manimlib import *
import numpy as np

class GeneratedMathScene(Scene):
    """
    Unit Circle Trigonometric Wave Generation
    Generated by MathMotion Studio
    """
    def construct(self):
        title = Title(r"Trigonometry: Unwinding the Sine Wave")
        title.set_color_by_gradient(CYAN, BLUE)
        self.play(Write(title))
        
        # Unit Circle on the left
        circle_center = LEFT * 3.5 + DOWN * 0.5
        radius = 1.8
        circle = Circle(radius=radius, color=BLUE, stroke_width=3).move_to(circle_center)
        axes_circle = Axes(x_range=[-1.5, 1.5, 1], y_range=[-1.5, 1.5, 1], width=4, height=4).move_to(circle_center)
        
        # Wave Axes on the right
        axes_wave = Axes(
            x_range=[0, 3 * PI, PI],
            y_range=[-1.5, 1.5, 1],
            width=6.5,
            height=4
        ).move_to(RIGHT * 2.5 + DOWN * 0.5)
        
        self.play(ShowCreation(circle), ShowCreation(axes_circle), ShowCreation(axes_wave))
        
        # Angle tracker
        theta = ValueTracker(0)
        
        # Rotating radius and projecting line
        def get_dot():
            ang = theta.get_value()
            return circle_center + np.array([radius * np.cos(ang), radius * np.sin(ang), 0])
            
        dot = always_redraw(lambda: Dot(get_dot(), color=YELLOW, radius=0.08))
        radius_line = always_redraw(lambda: Line(circle_center, get_dot(), color=YELLOW, stroke_width=2.5))
        
        # Projected horizontal line
        proj_line = always_redraw(lambda: DashedLine(
            get_dot(),
            axes_wave.c2p(theta.get_value(), np.sin(theta.get_value())),
            color=RED_B,
            stroke_width=1.5
        ))
        
        # Sine wave trace
        sine_curve = always_redraw(lambda: axes_wave.get_graph(
            lambda x: np.sin(x),
            x_range=[0, max(0.01, theta.get_value())],
            color=RED
        ))
        
        self.add(dot, radius_line, proj_line, sine_curve)
        self.play(theta.animate.set_value(2.5 * PI), run_time=6, rate_func=linear)
        self.wait(1)
'''
    return code


def _build_latex_proof_code(cfg: dict) -> str:
    steps = cfg.get("steps", [
        r"e^{i\theta} = \cos(\theta) + i\sin(\theta)",
        r"\text{Let } \theta = \pi",
        r"e^{i\pi} = \cos(\pi) + i\sin(\pi)",
        r"e^{i\pi} = -1 + 0",
        r"e^{i\pi} + 1 = 0"
    ])
    
    steps_repr = repr(steps)
    
    code = f'''from manimlib import *

class GeneratedMathScene(Scene):
    """
    Step-by-Step Mathematical Proof
    Generated by MathMotion Studio
    """
    def construct(self):
        title = Title(r"Step-by-Step Mathematical Morphing")
        title.set_color_by_gradient(GOLD_C, YELLOW_A)
        self.play(Write(title))
        
        proof_steps = {steps_repr}
        
        current_tex = Tex(proof_steps[0], font_size=44, color=WHITE).center()
        self.play(Write(current_tex), run_time=1.5)
        self.wait(0.8)
        
        for next_step_str in proof_steps[1:]:
            next_tex = Tex(next_step_str, font_size=44, color=YELLOW).center()
            self.play(TransformMatchingTex(current_tex, next_tex), run_time=1.5)
            current_tex = next_tex
            self.wait(0.8)
            
        box = SurroundingRectangle(current_tex, color=GOLD, buff=0.25)
        self.play(ShowCreation(box))
        self.wait(1.5)
'''
    return code


def _build_storyboard_code(cfg: dict) -> str:
    beats = cfg.get("beats", [])
    
    code = '''from manimlib import *
import numpy as np

class GeneratedMathScene(Scene):
    """
    Custom Storyboard Mathematical Scene
    Generated by MathMotion Studio
    """
    def construct(self):
'''
    if not beats:
        code += '''        title = Title("MathMotion Storyboard")
        self.play(Write(title))
        circle = Circle(color=BLUE, radius=2)
        self.play(ShowCreation(circle))
        self.wait(1)
'''
        return code

    for idx, beat in enumerate(beats):
        b_type = beat.get("type", "write_title")
        dur = float(beat.get("duration", 1.0))
        
        if b_type == "title":
            txt = beat.get("text", "Mathematical Concept")
            code += f'''        # Beat {idx+1}: Title
        t_{idx} = Title(r"{txt}")
        self.play(Write(t_{idx}), run_time={dur})
'''
        elif b_type == "formula":
            f_str = beat.get("latex", "f(x) = x^2")
            pos = beat.get("position", "center")
            code += f'''        # Beat {idx+1}: Formula
        tex_{idx} = Tex(r"{f_str}", font_size=40).{pos}()
        self.play(Write(tex_{idx}), run_time={dur})
'''
        elif b_type == "graph":
            func = beat.get("function", "np.sin(x)")
            code += f'''        # Beat {idx+1}: Axes and Function
        ax_{idx} = Axes(x_range=[-4, 4, 1], y_range=[-2, 2, 1], width=8, height=4.5)
        g_{idx} = ax_{idx}.get_graph(lambda x: {func}, color=YELLOW)
        self.play(ShowCreation(ax_{idx}), ShowCreation(g_{idx}), run_time={dur})
'''
        elif b_type == "wait":
            code += f'''        # Beat {idx+1}: Pause
        self.wait({dur})
'''
    code += '        self.wait(1)\n'
    return code


def _build_fallback_code(cfg: dict) -> str:
    return '''from manimlib import *

class GeneratedMathScene(Scene):
    def construct(self):
        title = Title("MathMotion Animation")
        self.play(Write(title))
        c = Circle(color=BLUE, radius=1.5)
        s = Square(color=YELLOW, side_length=2.5)
        self.play(ShowCreation(c))
        self.play(Transform(c, s))
        self.wait(1)
'''
